### PR TITLE
Internal module, conditional dependency on semigroups

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
I'm not sure about the last commit. IMHO it's good to bump versions early in repository when big enough changes are introduced.

**Comment by spl** [comment]
Thanks! A couple of things:

1. The `stimes` test fix is good.
2. Is the `dist-newstyle` from `cabal new-build`? I haven't used that, yet.
3. I'm not convinced of the need to export the `DList` constructor. See #4 and #14 for previous discussions.
4. Why make `semigroups` a dependency for older versions of GHC? I'd rather only introduce features for newer versions and not create an additional dependency. If you want the `Semigroup` instance for older GHC versions, use [`dlist-instances`](https://hackage.haskell.org/package/dlist-instances).

**Comment by phadej** [comment]
2. Yes, you should really try `cabal new-build`, unfortunately you'd need to use the `HEAD` version to get good experience.

3. I made https://github.com/phadej/dlist-nonempty and would like to have
```hs
toDList :: NonEmptyDList a -> DList a
toDList (NEDL f) = DList.DL (NE.toList . f)
```

IMHO having the constructor exposed in internal module is safe enough.

In #14 @sol said

> this makes `dlist` less useful, which would mean that I roll my own...

which is sad. The `Endo [a]` is good enough for internals, but you don't want to expose that to the public API.

Also using older version of `dlist` isn't really an option e.g. with Stackage.

4. Yes, it's an additional dependency with older `GHC`s, but `void`, `nats` and `semigroups` all fall in "practically unavoidable" in most applications. Also there additional compilation cost with `stack` or `cabal new-build` is negligible.

If you insist on not dependending on `semigroups` package, I'll add a note about existence of `dlist-instances`. I didn't remember it existed.

Yet, with `Semigroup` instance directly in `dlist`, `dlist-instances` as for now could be deprecated.

**Comment by spl** [comment]
Regarding `semigroups`, see #25. Regarding `dlist-instances`, see gregwebs/dlist-instances#2. I'm not going to add `semigroups` as a dependency.

Would you rather put `Data.DList.NonEmpty` in `dlist`? I'm certainly open to the idea.

**Comment by phadej** [comment]
If you willing to include `Data.DList.NonEmpty` in `dlist`, than you'll need to depend on `semigroups`...

**Comment by spl** [comment]
Why?

**Comment by phadej** [comment]
`NonEmpty` is defined in `Data.List.NonEmpty` which is only in `base-4.9` (or `semigroups`). I'm :-1: having the module only with `base-4.9`.

See: http://pvp.haskell.org/faq/#what-implications-does-the-pvp-have-for-conditional-apis

**Comment by spl** [comment]
I'm 👎 on introducing the tree of dependencies brought by `semigroups` to a package which has heretofore been lightweight. And since the `Semigroup` instance is already conditionally added, I see no reason not to conditionally include `Data.List.NonEmpty`.

**Comment by phadej** [comment]
well. I'm against conditional APIs. So for now, `dlist-nonempty` can be a separate package.

**Comment by phadej** [comment]
for the record, dependencies of dlist with `semigroups` (GHC-7.10.3)

- UnitID "builtin_rts"
- UnitID "ghc-prim-0.4.0.0-6cdc86811872333585fa98756aa7c51e"
- UnitID "integer-gmp-1.0.0.0-3c8c40657a9870f5c33be17496806d8d"
- UnitID "base-4.8.2.0-0d6d1084fbc041e1cded9228e80e264d"
- UnitID "array-0.5.1.0-960bf9ae8875cc30355e086f8853a049"
- UnitID "deepseq-1.4.1.1-614b63b36dd6e29d2b35afff57c25311"
- UnitID "bytestring-0.10.6.0-c60f4c543b22c7f7293a06ae48820437"
- UnitID "containers-0.5.6.2-e59c9b78d840fa743d4169d4bea15592"
- UnitID "binary-0.7.5.0-5784fd031a720c3b84e73006e444c7ca"
- **UnitID "text-1.2.2.1-a77d86770d0f3c5dd49e42e0b86178ac7560349c721dfdfc283975b42eca7c1b"**
- **UnitID "hashable-1.2.5.0-c3acc9933d524fc648e9d74403773a83820a81b7bbfbaac4c5f095213d865cd8"**
- UnitID "pretty-1.1.2.0-5cc412214ea63f61ee84c4fbabdbe0ec"
- UnitID "template-haskell-2.10.0.0-3c4cb52230f347282af9b2817f013181"
- UnitID "transformers-0.4.2.0-81450cd8f86b36eaa8fa0cbaf6efc3a3"
- **UnitID "transformers-compat-0.5.1.4-5f1497b2541962d48373277058585197adec39b90dbf245435018566c8592904"**
- **UnitID "tagged-0.8.5-c9d62b67116e4352cc98248bb2303d8cbf8c2dd89f620ef13dcd5585844d2e21"**
- **UnitID "unordered-containers-0.2.7.2-3e40637987999d8ff56b61b921e002a9922be82bcec9fe6ccb57d17be29d8ec6"**
- **UnitID "semigroups-0.18.2-5a2fbf1540c0401e11a2d0c374c6b6f59bff3e191229ff7e9a49cd39686fb9d1"**
- *UnitID "dlist-0.8.1-inplace"*

Bolded are dependencies brought in by `semigroups`, plain ones are bundled.

**Pull request closed without merging**
